---
- hosts: all
  gather_facts: false
  become: yes
  vars:
    git_repo: https://github.com/thedovekana/Deploy-sample-website-with-ansible-jenkins.git
  tasks:

    - name: Install the required packages
      package:
        name:
          - wget
          - unzip
          - httpd
          - git
        state: present
        update_cache: true
    
    - name: start and enable httpd service
      service:
        name: httpd
        state: started
        enabled: yes
     
    - name: Remove the default file
      command: rm -f /var/www/html/*
    
    - name: Create a temporary folder
      file:
        path: /tmp/website/
        state: directory
    
    - name: clone the website code
      git:
        repo: "{{ git_repo }}"
        dest: /tmp/website

    - name: copy the website files
      copy:
        src: /tmp/website/wave_cafe_project/
        dest: /var/www/html/ 
        remote_src: yes
   
    - name: restart httpd service
      service:
        name: httpd
        state: restarted
