---
- hosts: all
  gather_facts: false
  become: yes
  vars:
    git_repo: https://github.com/thedovekana/Deploy-sample-website-with-ansible-jenkins.git
  tasks:

    - name: Install the required packages
      package:
        name:
          - wget
          - unzip
          - nginx
          - git
        state: present
        update_cache: true
    
    - name: start and enable nginx service
      service:
        name: nginx
        state: started
        enabled: yes
     
    - name: clone the website code
      git:
        repo: "{{ git_repo }}"
        dest: /tmp/

    - name: Remove the default file
      command: rm -f /var/www/html/*

    - name: copy the website files
      copy:
        src: /tm/Deploy-sample-website-with-ansible-jenkins/wave_cafe_project/*
        dest: /var/www/html/ 
   
    - name: restart nginx service
      service:
        name: nginx
        state: restarted
